import { Inter } from "next/font/google";
import "./globals.css";

// Components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Fonts

import { Caveat, Jost } from "next/font/google";


// Themes Provider
import { ThemeProvider } from "@/components/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

const caveat_init = Caveat({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-caveat'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={caveat_init.variable}>
        <ThemeProvider attribute='class' defaultThemes='light'>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
